force-app/main/default/objects/Log__e/Log__e.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Log__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Messages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__e/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public with sharing class Logger {

    public static String getClassName(String line) {
        if (line.startsWith('Class.')) {
            line = line.substringAfter('Class.');
        }
        return line.substringBefore(':').substringBeforeLast('.');
    }

    public static String getMethod(String line) {
        return line.substringBefore(':').substringAfterLast('.');
    }

    public static String getStackTrace() {
        return new DmlException().getStackTraceString().split('\n').get(3);
    }
    public static void log(LoggingLevel level, String title, Object data) {
        log(level, title, Json.serialize(data)) ;
    }

    public static void log(LoggingLevel level, String title, List<Object> data) {
        log(level, title, Json.serialize(data)) ;
    }

    public static void log(LoggingLevel level, String title, String message) {
        String className = getClassName(getStackTrace());
        String method = getMethod(getStackTrace());
        Log__e log = new Log__e(level__c = level.name(), scope__c = (className +':' + method), title__c = title, message__c = message );
        Eventbus.publish(log);
    }

    public static void log(Exception e) {
        log(LoggingLevel.ERROR, e.getTypeName(), e.getStackTraceString().split('\n'));
    }


}